---
- name: Enforce root user configuration
  import_tasks: user_root.yaml

- name: Create infrastructure user
  import_tasks: user_infra.yaml

- name: Create Zincster user
  import_tasks: user_zinc.yaml

  - name: Create Zabbix user
  import_tasks: user_zabbix.yaml
