---
ntp_enabled: true
ntp_timezone: America/Boise

# ntp_daemon: [various]
# ntp_package: ntp
# ntp_config_file: /etc/ntp.conf
# ntp_driftfile: [various]

ntp_manage_config: true

# NTP server area configuration (leave empty for 'Worldwide').
# See: http://support.ntp.org/bin/view/Servers/NTPPoolServers
ntp_area: ''
ntp_servers:
  - "time1.body.prod iburst"
  - "time2.body.prod iburst"

ntp_restrict:
  - '127.0.0.1'
  - '::1'
  - '-4 default kod nomodify notrap nopeer noquery'
  - '-6 default kod nomodify notrap nopeer noquery'

ntp_cron_handler_enabled: false

ntp_tinker_panic: false
