---
# handlers file for ansible-role-autofs

- name: "restart autofs"
  service: name=autofs state=restarted
  when: ansible_system == 'Linux'

- name: "reload autofs"
  service: name=autofs state=reloaded
  when: ansible_system == 'Linux'
